"""
JARVIS Sentinel - Core Models
Structured domain models for multi-agent security operations and policy decisions.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EndpointStatus(str, Enum):
    CONNECTED = "CONNECTED"
    ISOLATED = "ISOLATED"
    QUARANTINED = "QUARANTINED"


class IncidentStatus(str, Enum):
    DETECTED = "DETECTED"
    INVESTIGATING = "INVESTIGATING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    REMEDIATING = "REMEDIATING"
    RESOLVED = "RESOLVED"
    DENIED = "DENIED"


class PolicyAction(str, Enum):
    AUTO_RESOLVE = "AUTO_RESOLVE"
    INVESTIGATE_ONLY = "INVESTIGATE_ONLY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    BLOCK_AND_ALERT = "BLOCK_AND_ALERT"


class SecurityEvent(BaseModel):
    """Raw or parsed security event (Sysmon/EDR/CloudTrail)."""
    event_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    host_id: str
    user: str
    event_type: str  # PROCESS_CREATE, NETWORK_CONNECT, FILE_MODIFY, REGISTRY_SET
    process_name: Optional[str] = None
    process_id: Optional[int] = None
    parent_process: Optional[str] = None
    command_line: Optional[str] = None
    dest_ip: Optional[str] = None
    dest_port: Optional[int] = None
    file_path: Optional[str] = None
    sha256: Optional[str] = None
    details: Dict[str, Any] = Field(default_factory=dict)


class ProcessNode(BaseModel):
    pid: int
    name: str
    cmdline: str
    parent_pid: Optional[int] = None
    children: List[int] = Field(default_factory=list)
    is_suspicious: bool = False
    indicators: List[str] = Field(default_factory=list)


class ThreatIndicator(BaseModel):
    indicator: str
    type: str  # IP, HASH, DOMAIN
    reputation: str  # MALICIOUS, SUSPICIOUS, BENIGN, UNKNOWN
    score: float = Field(ge=0.0, le=100.0)  # 0 to 100 confidence
    mitre_techniques: List[str] = Field(default_factory=list)
    threat_actor: Optional[str] = None
    details: str = ""


class InvestigationResult(BaseModel):
    """Correlated forensic evidence gathered by the Investigator Agent."""
    host_id: str
    correlated_events_count: int
    matched_events: List[SecurityEvent] = Field(default_factory=list)
    process_tree: List[ProcessNode] = Field(default_factory=list)
    external_ips: List[str] = Field(default_factory=list)
    modified_files: List[str] = Field(default_factory=list)
    indicators: List[ThreatIndicator] = Field(default_factory=list)
    blast_radius: str = "Host-only"
    summary: str = ""


class RiskAssessment(BaseModel):
    """Risk Agent evaluation."""
    severity: RiskLevel
    confidence: float = Field(ge=0.0, le=1.0)
    primary_threat: str
    evidence_count: int
    suspected_behavior: str
    recommended_action: str
    potential_impact: str
    reasoning: str


class PolicyDecision(BaseModel):
    """Deterministic decision generated by the Policy Engine."""
    risk_level: RiskLevel
    action_permitted: bool
    requires_hitl: bool
    policy_rule_id: str
    explanation: str
    allowed_remediation_actions: List[str]
    authorized_by: str = "DeterministicPolicyEngine"


class IncidentBrief(BaseModel):
    """Evidence-backed incident card for human review or autonomous audit."""
    incident_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    affected_host: str
    confidence: float
    evidence_count: int
    suspected_behavior: str
    recommended_action: str
    potential_impact: str
    status: IncidentStatus
    risk_level: RiskLevel
    requires_hitl: bool
    investigation_summary: str
    policy_decision: Optional[PolicyDecision] = None
    timeline: List[str] = Field(default_factory=list)
    remediation_result: Optional[str] = None


class TraceEvent(BaseModel):
    """Fine-grained timestamped trace of agent execution."""
    trace_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    agent_name: str
    action_type: str  # DISPATCH, TOOL_CALL, TOOL_RESULT, POLICY_CHECK, HITL_GATE, REMEDIATION
    message: str
    payload: Dict[str, Any] = Field(default_factory=dict)
